config/routes.rb
Rails.application.routes.draw do
  
  root "static_pages#home"
  
  get '/home', to:'static_pages#home'
  get '/about', to:'static_pages#about'
  get '/contact', to:'static_pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    
    before_save{self.email=email.downcase}
    
    valid_regex=/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i;
    
    validates :name, presence:true, length:{maximum:50}
    validates :email, presence:true, length:{maximum:50}, format:{with:valid_regex},uniqueness:{case_sensitive:false}
    
    validates :password, presence:true, length:{minimum:6}
    
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def index
       render html: "hello world"  
    end
    
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
  
  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def titlegrabber(title="")
    
    
    base_title="Rails Application"
    
    if title.empty?
        base_title
    else
        title+base_title
    end
    
        
    end
    
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
  <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "sample app", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",  root_path %></li>
            <li><%= link_to "Help",  '#' %></li>
            <li><%= link_to "Contact", contact_path %></li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= titlegrabber(yield(:title))%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/header" %>
    <div class="container">
      
       <%= yield %>
       
    </div>

   <%= render "layouts/footer" %>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title,"About") %>
<h1>About Page</h1>
<p>About page content and components will be available here shortly</p>

app/views/static_pages/contact.html.erb
<% provide(:title,"contact") %>

<h1>Contact Page</h1>
<p>This space will be filled with the content and the components shortly</p>

app/views/static_pages/home.html.erb
<% provide(:title, "")%>

<div class=" center jumbotron">
    
<h1>Rails Sample Application Homepage</h1>

<p>home page contents and components will be available here shortly</p>

<%= link_to "Sign Up", "#", class:"btn btn-primary" %>

</div>

<%= link_to image_tag("https://avatars.githubusercontent.com/u/4223",alt:"rails image"), "#" %>